### ISSUE TITLE
Uploading data: This path did not match any routes.

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#147]
Trying to upload new data, but get the message that the path did not match any routes. Refreshed the page a few times, but I can't upload new data

**Steps to reproduce**
1. Go to Admin panel, Data sets
2. Click on new data, click on data, click on new data
4. See "The path did not match any routes." 

**Browser**
Chrome

**Expected behavior**
Expected the window where I can upload data

**Comment by imathews** [comment]
@sannesmith this is a known bug that we've opted not to fix in order to focus our efforts on the new uploader, which will be far more stable and offer some highly requested functionality.

You'll often be able to resolve issues like this by reloading the page or re-navigating to the uploader. The URL scheme of the uploader will always look like `https://redivis.com/StanfordPHS/datasets/[Dataset_Id]/uploader`, you can also navigate to this URL manually.

Please let us know if this bug is preventing you from moving forward with your work, but otherwise, if it's just an annoyance, hopefully you can work around it and thanks for bearing with us as we work to bring the new uploader live.
