### ISSUE TITLE
Download *all* the SQL code used to produce the table

### ISSUE THREAD

**Issue by halflearned** [redivis/meta#176]
The [documentation on exporting](https://docs.redivis.com/projects/saving-and-exporting) states that 

> Metadata downloads
> All tables and saved tables allow you to download a SQL file with **all code** that was generated to create that table.

However, when we click on Downloads > SQL used to generate table, we only get the code for the last query. In fact, we would like to get _all_ the SQL code, starting at the top of the graph.

**Comment by imathews** [comment]
Thanks @halflearned  — the expected behavior is to produce the full SQL code from the top of the tree.

I just tested on [this public project](https://redivis.com/projects/2343/tables/42092?exportTableId=42092), and the code generated did include all previous transforms. Could you point me to an example where this isn't happening so we can investigate further?

**Comment by imathews** [comment]
@halflearned Closing this issue, as I believe the current functionality captures what you're looking for here. Let us know if that's not the case.
