### ISSUE TITLE
Redivis not responding to `startIndex`

### ISSUE THREAD

**Issue by jmbott** [redivis/meta#183]
**Describe the bug**
On API query Redivis seems to not listen to `startIndex` parameter. Returns the same results regardless of what `startIndex` value is requested. It is still listening to the `maxResults` parameter though. 

**Steps to reproduce**
see https://github.com/SEL-Columbia/cwp-epu-data-platform/issues/109

example endpoint, 
`https://redivis.com/api/v1/tables/modilab.uganda_geodata:3.uganda_geosurvey_results:2/rows?selectedVariables=lat,lon&maxResults=10000&startIndex=30000`

**Browser**
chrome

**Expected behavior**
when polling the endpoint with `startIndex=30000` data starting from that point should be returned.

**Any additional context**
with the requests, 

`https://redivis.com/api/v1/tables/modilab.uganda_geodata:3.uganda_geosurvey_results:2/rows?selectedVariables=lat,lon&startIndex=0&maxResults=10`
and
`https://redivis.com/api/v1/tables/modilab.uganda_geodata:3.uganda_geosurvey_results:2/rows?selectedVariables=lat,lon&startIndex=10&maxResults=10`

the results are (concated together)
```
0: (2) ['1.020995', '34.021595']
1: (2) ['1.828737', '33.543188']
2: (2) ['0.417348', '30.549861']
3: (2) ['0.417942', '32.658993']
4: (2) ['0.531677', '33.592721']
5: (2) ['3.101967', '31.459982']
6: (2) ['1.724626', '33.974184']
7: (2) ['2.471663', '33.761335']
8: (2) ['2.169742', '33.309522']
9: (2) ['0.933603', '33.607041']
10: (2) ['1.020995', '34.021595']
11: (2) ['1.828737', '33.543188']
12: (2) ['0.417348', '30.549861']
13: (2) ['0.417942', '32.658993']
14: (2) ['0.531677', '33.592721']
15: (2) ['3.101967', '31.459982']
16: (2) ['1.724626', '33.974184']
17: (2) ['2.471663', '33.761335']
18: (2) ['2.169742', '33.309522']
19: (2) ['0.933603', '33.607041']
```

where the 10 pairs of initial data returned are the same as the second set returned.

**Comment by imathews** [comment]
Hi @jmbott, thanks for the detailed report. Confirmed that we're seeing something similar in our logs, I think I know what might be going on here — I'll try to have a look this weekend and will follow up shortly.

**Comment by imathews** [comment]
@jmbott I wanted to update that I've almost completed a fix for this, and should be able to get you a resolution by EOD tomorrow.

**Comment by imathews** [comment]
@jmbott I just filed a PR (https://github.com/SEL-Columbia/cwp-epu-data-platform/pull/110) that resolves this issue. It leverages the new [redivis-js](https://apidocs.redivis.com/client-libraries/redivis-js) library rather than making API calls directly, which should be simpler and more robust.

In order to improve performance, we needed to remove pagination from our `table/listRows` endpoint — the updated endpoint can now be used to stream an unbounded number of records at once, so pagination is no longer required. The redivis-js library handles this properly, but it was incompatible with how we were handling large results in the previous implementation.

I've made sure to update our API documentation so that it's consistent with the new behavior. Marking this as resolved, but please feel free to reopen if you run into any further issues!
