### ISSUE TITLE
Nested Arithmetic Methods in Interface Transform Aren't Being Evaluated Correctly

### ISSUE THREAD

**Issue by zmorganABFM** [redivis/meta#191]
**Describe the bug**
I'm trying to perform a conversion of A1C levels from mg/dL to A1C% using a transform in interface mode. This conversion follows the formula `want = (have + 46.7) / 28.7`. Because the Arithmetic method only allows a single operation per use, I had to create an intermediate variable `intermediate = have + 46.7` before creating my final variable as `want = intermediate / 28.7`. I expected the intermediate evaluation to be completed before the final calculation but after looking at the code generated by the interface, I see that is not the case. As shown in the included screenshots, this nesting of methods results in the following evaluation: `have + 46.7 / 28.7 AS want` which will not evaluate in the correct order. As an example, a value of 150 would evaluate to ~151.6 instead of the correct value of ~6.85.

**Steps to reproduce**
1. Use nested arithmetic methods in an interface transform to perform the above conversion.
2. Observe that the intermediate step is not necessarily completed before the final step.
3. See the resulting incorrect conversions.

**Browser**
Chrome

**Expected behavior**
I would expect that the intermediate calculation would be completed before the final calculation. That is, I would expect the generated code to read `(have + 46.7) / 28.7 AS want` which would ensure the proper evaluation order.

**Screenshots**
![redivisBug_interface_061522](https://user-images.githubusercontent.com/104507846/173912393-78a10967-0e05-4a92-a76a-a835e57f23e8.PNG)
![redivisBug_code_061522](https://user-images.githubusercontent.com/104507846/173912386-7487667e-d447-4a87-ad80-6d46748570c1.PNG)

**Any additional context**

**Comment by imathews** [comment]
Hi @zmorganABFM — thanks so much for opening this issue. We just pushed an update that should resolve this bug (we now always wrap arithmetic functions in parentheses when generating the SQL).

FYI, we do have some updates planned that will make writing complex arithmetic operations a lot more streamlined, rather than needing to create multiple variables as you did here (I appreciate this isn't the most elegant). But in the meantime, this is the best approach, or alternatively you can always write your own custom SQL in the editor.

Please don't hesitate to reach out if you have any further questions / issues!
