### ISSUE TITLE
Ability to kill queries

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#39]
Hi Redivis,

I have two queries that have been running for more than 20 minutes and I am unable to kill them (see below). They usually take less than 2 minutes:
![screen shot 2017-06-28 at 10 27 28 am](https://user-images.githubusercontent.com/22604632/27651280-9d5ddb98-5bec-11e7-8ec5-f1729e88f98e.png)
It'd be great to have a "cancel" button.

Thanks!
Valerie

**Comment by imathews** [comment]
@vmeau definitely agree on the cancel button; we'll try to roll that out shortly. The fact that these are taking so long is actually due to #41 — a known issue that we're working to resolve shortly (though a non-trivial thing to implement). This is the same as @emmahallgren's issue #40 

TLDR; I deployed a patch earlier this morning while your jobs were running, causing them to indefinitely hang. I'm going to manually set these to `failed`, so you will then be able to rerun them.

**Comment by imathews** [comment]
Transform and join jobs are now cancellable
