### ISSUE TITLE
Streaming data to BigQuery - takes very long time

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#40]
I uploaded the Truven 2015 data yesterday, it seems like it's still streaming. Is it normal that it takes so much time? 

![screen shot 2017-06-28 at 10 27 57 am](https://user-images.githubusercontent.com/29311144/27651386-fe520352-5bec-11e7-86f3-4ab199bb5016.png)

Thanks!

**Comment by imathews** [comment]
Sorry about this @emmahallgren — this is actually a result of #41, which we're working to fix asap.

I deployed a patch earlier this morning while your jobs were running, causing them to indefinitely hang. I'm going to manually set this job to `failed`, so you will then be able to rerun it. In my experience, even uploading the biggest datasets to bigquery takes no more than 1hr.

**Comment by emmahallgren** [comment]
I tried to rerun a couple of them, maybe I was too early, because it still seems to go quite slow. Not as bad as earlier, but considering how small some of the files are in comparison to the previous ones.

**Comment by imathews** [comment]
Hmm... have any of them successfully finished? I see there are still four jobs running, so there might be a bigger issue with data imports right now...

I'm traveling today and will have limited ability to debug this, but will tackle first thing tomorrow

**Comment by emmahallgren** [comment]
No, none of them have finished. I guess I will wait with the rest until it's resolved. Thanks for checking!

**Comment by emmahallgren** [comment]
Any news regarding the 2015 data? I see that it's still pending. Thanks!

**Comment by imathews** [comment]
On my to-do list — will hop on shortly :)

**Comment by emmahallgren** [comment]
Sorry, I saw that you just mentioned this!

**Comment by imathews** [comment]
I've diagnosed the problem here; related to the mismatched columns in Truven (it was fixed, and then something must've gotten changed that's now causing errors). The second bug is that these errors aren't causing the job to be marked as failed.

I'll aim to fix both by eod, and will update once these fixes are live

**Comment by imathews** [comment]
@emmahallgren I've been able to make a fair amount of progress on this, but still not quite fixed (sorry) — will hop on first thing tomorrow; i'm on east coast time now - in theory - so might be done by the time you're all up and running.

**Comment by emmahallgren** [comment]
No worries, thanks for working so hard on this.

**Comment by imathews** [comment]
@emmahallgren This should now be fixed. The underlying issue was with adding a new file (after some files had been uploaded) which had schema that did not match the current table. In this case, we have to track that difference and update the previous table before appending any new uploads.

I also fixed some of the issues with jobs — hopefully, whenever an error occurs, they should at least fail and give you feedback, rather than having a stalled progress bar indefinitely.

Marking this as closed, though certainly could stand to be tested a bit more, and please do open new issue(s) if you run into further problems

Thanks!!
