### ISSUE TITLE
Data uploader

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#83]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

Thank you for being a beta tester of Redivis. Your feedback is invaluable to our development :)
-->

**Browser** (e.g., Chrome, Safari, etc.):
Chrome and Safari, on iPad

**What happened**:
Data uploader- when I click on the node, the page goes blank except for the banner at the top. This could be an iPad issue? If so, not a high priority

**Comment by imathews** [comment]
@lesleyspark yea this is a Safari / Webkit bug that's happening in a few places. We'll try to sort out, though a new version of safari will be released next week for iOS and macOS that should fix this

**Comment by imathews** [comment]
In the meantime, Chrome / Firefox should solve your problems

**Comment by imathews** [comment]
This issue is resolved with the release of Safari 11 and iOS 11 (released yesterday 9/19). I know that not all of our users will immediately upgrade, but the fix for Safari < 11 would lead to pretty significant performance degradations for the rest of our users. Since most people are already on Chrome on desktop, I'm going to close this and mark as a wontfix, with the solution being to upgrade your mac / iOS devices
