### ISSUE TITLE
# distinct in variable summary inconsistent

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#87]
BUG

<!--
If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
    information, we can't help you as well.

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I was looking up the number of unique patients in the Optum SES files. My numbers on the server don't match what's on redivis. for example - 
for Optum SES member detail, I have 67,582,529 patients, and redivis shows 67,447,758
For Optum SES SES, I have 57,426,787 patients, redivis shows 57,307,682

**Comment by lesleyspark** [comment]
woah, weird, I think my bug report got deleted somehow! this is what I wrote:

I'm getting different numbers (on the server) for "distinct". for example:
SES Member:  67,582,529, on redivis: 67,447,758
SES SES: 57,426,787, on redivis: 57,307,682

**Comment by imathews** [comment]
@lesleyspark we've been using an approximate distinct to improve performance, but have reverted back to the true distinct in an update that should be released this afternoon. We'll reset the cached statistics accordingly.

FYI, your original message didn't come through because it got mangled with the commented text (anything between `<!--` and `--!>` won't show up. The best thing to do is just to delete some of the template text as you go through.

**Comment by imathews** [comment]
fixed in https://github.com/redivis/meta/releases/tag/0.2.2
