### ISSUE TITLE
Casting to a different type

### ISSUE THREAD

**Issue by llamsam** [redivis/meta#88]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**:

I was attempting to cast the ENROLID variable in the Truven enrollment detail table from FLOAT64 to STRING (the other tables had ENROLID as STRING already, so this difference prevented merging on ENROLID). I submitted the below command, which did produce a table. However, I was unable to view the cells in the resulting table or subsequently merge it with another table.

SELECT CAST($ENROLID AS STRING) AS $ENROLID, $DTEND, $DTSTART FROM ``

**What you expected to happen**: I expected it to produce a table with columns ENROLID, DTEND, and DTSTART that could be viewed and subsequently manipulated. I expected that ENROLID would be a STRING, which I could not determine because the variable information screen would not populate.

**How to reproduce it** (as minimally and precisely as possible): See above. There are not any dependencies, so recreating this error should be straightforward.

**Anything else do we need to know**: I confirmed that BigQuery's Standard SQL allows casting from FLOAT64 to STRING.

**Comment by imathews** [comment]
Hi @llamsam — thanks for the detailed report. The issue here is that the previous query is throwing a (cryptic) error. 

In our current SQL markup, dollar signs should only be prefixed to variables that are being referenced in the previous table, not on new variables that are being created (this allows for our parser to easily determine which variables are being referenced from the previous table). `AS $ENROLID` should be `AS ENROLID`, with the full query looking like:
```
SELECT CAST($ENROLID AS STRING) AS ENROLID, $DTEND, $DTSTART FROM ``
```

This is admittedly confusing and was a stopgap measure to allow us to release the initial version of the project tool. We aim to deploy a completely revamped querying system within the next two weeks that will alleviate a lot of these pains. Stay tuned, and keep the bugs / questions coming!
