### ISSUE TITLE
Uploading error - tsv files 

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#90]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report 

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I am trying to load a tsv file. Ian had fixed an issue in which "odd" variable characters are replaced by underscores. However, not all files I am trying to load have variable names, and some have long text entries, which may or may not be causing my upload to file. The error I get on the upload, for all files, is "Invalid opening quote at line 3"
![screen shot 2017-10-10 at 9 12 20 am](https://user-images.githubusercontent.com/22604632/31397570-334740b8-ad9b-11e7-9b4a-5208cbdf69f1.png)

**What you expected to happen**: I would like to be able to upload the tsv files. 

**How to reproduce it** (as minimally and precisely as possible):
1) Access the following bucket : https://console.cloud.google.com/storage/browser/som-researchit-phs-truven-omop_v5/vocabulary/extract/?project=som-researchit-phs

2) Copy the link to the file V5_Vocabulary.tsv

3) Go to the Redivis file uploader and upload the file, choosing "tab" as the delimiter. Click upload

**Anything else do we need to know**:

**Comment by imathews** [comment]
Thanks for the detailed report @vmeau. I'll look into this today and keep you posted

**Comment by imathews** [comment]
This is fixed in https://github.com/redivis/meta/releases/tag/0.3.2 — this actually wasn't an issue with the tsv, but rather that it wasn't using the standard quote character `"` — you can now change the default character to something else (including nothing); in this case, I imagine that there was no quote character for the file, meaning that a `"` should just be parsed as normal.
