### ISSUE TITLE
frequency tab not available for some variables

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#98]
BUG REPORT
**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
In the claims datasets, I am unable to see the frequencies for the diagnosis code variables as I was able to see previously. For variables with fewer categories, I was able to see, per normal.

**Comment by imathews** [comment]
@lesleyspark could you direct me to a specific dataset + variable where this is happening?

**Comment by lesleyspark** [comment]
Optum SES Medical, diag1-diag25

**Comment by imathews** [comment]
@lesleyspark This is consistent with the behavior we were seeing before; our cutoff for frequency distributions was 64k distinct values. Some of the Optum datasets have over 100k. 

I'm going to leave this open to reconsider what our threshold is here, though ultimately we will need to set some max limit. There are some reasons to keep it at 64k (e.g., can store as 16bit integer). We should probably have more user info when the frequency distribution is not available.

**Comment by imathews** [comment]
@lesleyspark This has now been implemented — for the frequency distribution, we now only show the top 10k values (allowing us to efficiently store statistics), but we can now display this for variables that have many millions of distinct values.

We still don't display frequency distribution in cases where the duplication rate is fairly low (e.g., Patid), since this doesn't really make sense
